package framework.bean.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Autogenerated {

    /**
     * defines a name of the field that will be used to soft collection.
     * Collection.sort(ArrayList&lt;Map&lt;Object,Object&gt;, AbstractDto&gt;)
     * @return value
     */
    String[] value() default "";
}
